apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: NAMESPACE
spec:
  targetNamespaces:
  - NAMESPACE

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/grafana-operator.grafana: ''
  name: grafana-operator
  namespace: NAMESPACE
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v4.2.0

---

apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  client:
    preferService: true
  config:
    auth:
      disable_login_form: false
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: error
      mode: console
    log.frontend:
      enabled: true
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  ingress:
    enabled: true
    path: /
    pathType: Prefix
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  service:
    labels:
      app: grafana
      type: grafana-service
    name: grafana-service

---

